version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: booksearch_db
      POSTGRES_USER: booksearch_user
      POSTGRES_PASSWORD: 12345
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend-net 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U booksearch_user -d booksearch_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./public:/app/public
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://booksearch_user:12345@db:5432/booksearch_db
    networks:
      - backend-net
    command: /app/entrypoint.sh

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
    environment:
      - BASIC_AUTH_USER=admin
      - BASIC_AUTH_PASSWORD=12345
    depends_on:
      - web
    networks:
      - backend-net

volumes:
  pgdata:

networks:
  backend-net:
    driver: bridge
